/**
 * Types for the IronmanCoach morning feed (`feed-v1`).
 *
 * The engine writes one of these per athlete per day:
 *   reports/athletes/<id>/feed_<YYYY-MM-DD>.json
 *
 * SOURCE OF TRUTH, in this order:
 *   1. the real files in ./fixtures/ — generated by `py tools/demo_data.py`
 *   2. src/delivery/feed.py in the engine repo
 *   3. docs/feed_schema.md — prose, and in four places it disagrees with (1)
 *
 * Every field below was checked against six generated feeds. Where the doc
 * and the engine disagree, the type follows the ENGINE and says so, because
 * the engine is what your app will actually receive.
 *
 * Three reading rules that are product promises, not styling choices:
 *   - `null` means UNKNOWN. Render it as unknown. Never substitute 0.
 *   - `warnings` outrank everything else visually.
 *   - `tier: "general"` content must be visibly labelled as a general
 *     estimate rather than this athlete's own measurement.
 */

// ---------------------------------------------------------------- top level

export interface Feed {
  /** Shape of this file. Check before parsing; changes only on a breaking change. */
  schema_version: "feed-v1" | string;
  athlete_id: string;
  /** The day described, YYYY-MM-DD, in the athlete's own timezone. */
  date: string;
  /** ISO timestamp. Days old ⇒ the scheduled job has a problem. */
  generated_at_utc: string;
  config_version: string;
  /** True while the athlete has no training data at all — lead with setup, not empty charts. */
  new_athlete: boolean;
  /** Wrong with the DATA, not with the athlete. Show above everything. */
  warnings: FeedWarning[];
  today: Today;
  recovery: Recovery;
  headline: Headline;
  sleep: Sleep;
  /** null for an athlete with no day before this one. */
  yesterday: Yesterday | null;
  week: Week;
  watch: Watch;
  figures: Figure[];
  /** The single most valuable thing the athlete could do next, or null. */
  next_unlock: string | null;
}

// ------------------------------------------------------------------ warnings

/**
 * `(string & {})` on every engine-supplied enum below is deliberate. It keeps
 * editor autocomplete for the known values while still accepting an unknown
 * one, because nothing validates these strings at the boundary — the engine
 * already emits an undocumented `today.source`. Always switch with a default
 * branch; never assume one of these unions is closed.
 */
export type WarningKind =
  /** A daily job has stopped. The numbers are not refreshing. */
  | "scheduled_job_not_running"
  /** The data itself is old. */
  | "data_freshness"
  /** Calendar days with no record; fitness numbers assume zero training on them. */
  | "missing_days"
  | (string & {});

export interface FeedWarning {
  kind: WarningKind;
  /** Already written for a human. Display verbatim; do not reword. */
  text: string;
}

// --------------------------------------------------------------------- today

/**
 * MISMATCH #1 — docs/feed_schema.md lists calendar | draft | starter | none.
 * The engine also emits "unplanned", which is what 5 of 6 generated athletes
 * carry. Handle it, and never assume this union is closed: switch with a
 * default branch rather than exhaustively.
 */
export type PlanSource =
  | "calendar"   // the uploaded block on the athlete's intervals.icu calendar
  | "draft"      // planned locally, not uploaded yet
  | "starter"    // GENERAL starter week from stated frequency — label as generic
  | "none"       // documented; not observed in any generated feed
  | "unplanned"  // NOT in the schema doc; emitted by the engine
  | (string & {});

export interface PlannedSession {
  name: string | null;
  /** Ride / Run / Swim / … */
  type: string | null;
  /** null ⇒ say the length is unknown. Do not guess. */
  duration_min: number | null;
  /** Why this session exists, one sentence. */
  objective: string | null;
  /** General fuelling guidance — never a personalised prescription. */
  fuelling: string | null;
}

export interface Today {
  source: PlanSource;
  /**
   * MISMATCH #2 — do NOT trust this string when `sessions` is empty.
   * feed.py always looks up the "none" wording once the session list is
   * empty, so a genuine starter rest day reads "no plan exists for this day"
   * while `source` says "starter" and `rest_day` is true. The schema doc's
   * own instruction is the opposite: show "rest day", not "nothing
   * scheduled". Derive your wording from `source` + `rest_day`, not here.
   */
  source_meaning: string;
  /** True ⇒ the starter plan deliberately reserves today as rest. */
  rest_day: boolean;
  /** Empty in all six generated feeds — this branch has no fixture coverage. */
  sessions: PlannedSession[];
}

// ------------------------------------------------------------------ recovery

export type RecoveryMetric = "hrv" | "rhr" | "load" | (string & {});

/**
 * Shapes taken from feed.py `_recovery_block`. No generated athlete fired a
 * flag, so none of this is fixture-covered — treat every member as optional.
 */
export interface RecoveryFlag {
  metric: RecoveryMetric;
  /** "alarm" is stronger than "flag". */
  severity: "flag" | "alarm";
  /** hrv only. */
  sd_below?: number | null;
  /** rhr only. */
  above_usual_bpm?: number | null;
  /** load only. */
  ratio?: number | null;
}

/** Above the athlete's usual range but NOT at flag level. Render CALM. */
export interface WorthALook {
  metric: "hrv" | "rhr";
  today: number | null;
  usual: number | null;
  sd_below?: number | null;
  above_usual_bpm?: number | null;
}

export interface Recovery {
  flags: RecoveryFlag[];
  worth_a_look: WorthALook[];
  /** The brief's exact recovery sentence. Safe prose fallback. */
  summary: string;
}

// ------------------------------------------------------------------ headline

export interface Headline {
  /**
   * The last COMPLETE day these numbers describe — never today, which is
   * always still in progress. null ⇒ every number below is null too.
   */
  as_of_date: string | null;
  /** Fitness. Slow-moving average of training load. */
  ctl: number | null;
  /** Fatigue. Fast-moving average. */
  atl: number | null;
  /** Fitness minus fatigue. Negative = carrying fatigue. */
  form: number | null;
  /** How long running tissue has been loaded. NOT calendar history. */
  run_training_age_weeks: number | null;
  /** Run-only acute:chronic ratio. null when history is too short to be honest. */
  run_acwr: number | null;
  /** One sentence explaining null numbers; null when they are present. */
  reason: string | null;
}

// --------------------------------------------------------------------- sleep

/**
 * Facts only — no flag fires here, because this system has no measured or
 * cited sleep threshold. `score` is the DEVICE's proprietary number: only
 * its trend within one device means anything. Label it as the watch's.
 */
export interface Sleep {
  date: string;
  /** null ⇒ nothing synced. Never render a device gap as "0h slept". */
  secs: number | null;
  score: number | null;
  /** The athlete's own average; null while still building. */
  baseline_secs: number | null;
  nights_in_baseline: number;
  /** The brief's exact sleep sentence. */
  text: string;
}

// ----------------------------------------------------------------- yesterday

export interface LoggedSession {
  type: string;
  duration_min: number | null;
}

export interface Yesterday {
  date: string;
  /** false ⇒ "not synced yet". NEVER render this as "you rested". */
  synced: boolean;
  load: number | null;
  form: number | null;
  /** null on the athlete's first day. */
  form_change: number | null;
  sessions: LoggedSession[];
  /** The brief's one-sentence reading; null when `synced` is false. */
  read: string | null;
}

// ---------------------------------------------------------------------- week

export type Discipline =
  | "swim" | "bike" | "run" | "strength" | "other"
  | (string & {});

export interface Week {
  /** The Monday the window opens on. Window is Monday → feed date, inclusive. */
  week_start: string;
  /** True ⇒ render "the week starts today", not "nothing logged". */
  is_first_day: boolean;
  sessions: number;
  moving_secs: number;
  load: number;
  /** Moving seconds per discipline. Empty object in every generated feed. */
  by_discipline: Partial<Record<Discipline, number>>;
  trained_last_7: number;
  /**
   * MISMATCH #3 — the schema doc says this is null when there is not enough
   * history, and explicitly "never rendered as 0". The engine emits 0.0 for
   * the beginner athlete. Treat 0 as unknown as well as null.
   */
  expected_per_week: number | null;
  /** Current consecutive untrained days. */
  gap_streak: number;
  behind_schedule: boolean;
}

// --------------------------------------------------------------------- watch

export type Confidence =
  | "HIGH" | "MODERATE" | "LOW" | "INSUFFICIENT_DATA"
  | (string & {});

export interface WatchItem {
  /** Machine name of the metric, e.g. "ramp_volume_run". */
  name: string;
  /** What it is about, in plain English. */
  label: string;
  /** How much data is behind it. */
  confidence: Confidence;
  /** True ⇒ a partial figure. NEVER show the number without saying so. */
  degraded: boolean;
  /** The confidence + partial-figure wording the brief uses. */
  note: string;
  /** The engine's own interpretation sentence. Display verbatim. */
  text: string;
}

export interface Watch {
  /**
   * USUALLY 2 — but the list can be longer, and the UI must not slice it.
   *
   * The daily budget applies to ROUTINE readings only. A BREACH — a reading
   * that crossed a limit — is never held back: `contract.py` returns
   * `breaches + routine[:room]`, so a day with three real breaches produces
   * three lines. The engine's own reasoning: applying the budget to breaches
   * "does the opposite of its purpose — it makes the brief short by removing
   * precisely the findings the athlete needed".
   *
   * There is no separate `breach` field. When a breach reason would otherwise
   * be dropped, the engine appends it to `text`.
   */
  items: WatchItem[];
  /** Further ROUTINE readings computed but held out of today's budget. */
  held_back: number;
}

// ------------------------------------------------------------------- figures

export type Tier =
  /** Computed from THIS athlete's own measurements. */
  | "personal"
  /** An honest population estimate. MUST be visibly labelled as general. */
  | "general"
  /** The system refuses to show anything — see why_no_general_fallback. */
  | "unavailable"
  | (string & {});

/** One capability, straight from the engine's own ladder. */
export interface Figure {
  /** Stable machine name, e.g. "easy_zone". Safe to key UI state on. */
  key: string;
  label: string;
  tier: Tier;
  /** What would raise the tier. Starts with "nothing" when already maxed. */
  unlocked_by: string;
  /** `unavailable` rows only: why no general estimate is offered. */
  why_no_general_fallback: string | null;
  /**
   * True ⇒ real data, but NOT the shape of answer the label promises
   * (usually a three-way split reported two ways because LT1 is unmeasured).
   * Never show a degraded figure without its reason NEXT TO IT, not in a
   * tooltip.
   */
  degraded: boolean;
  degraded_reason: string | null;
  /** Which engine metric the tier was read off, or null if config-decided. */
  evidence: string | null;
}
